### PR TITLE
request response logger middleware

### PR DESCRIPTION
**Pull request by perkops**

### CODE REVIEW

**Review by davidkallesen — APPROVED** [review]

**Comment by christianhelle** [comment]
Why?

Doesn't this work? https://learn.microsoft.com/en-us/aspnet/core/fundamentals/http-logging/?view=aspnetcore-7.0 for you?

**Comment by christianhelle** [comment]
If we're building HTTP logging tooling then we should at least address the issues that the built-in HTTP Logging tooling lacks, like data scrubbing...

**Comment by christianhelle** [comment]
We use the built-in HTTP logging in 2 projects and have custom logging on another. The solution where we used custom logging was a payment system and we needed to scrub out payment details and PII's

We use the built-in HTTP logging like this

```csharp
builder.Services.AddApplicationInsightsTelemetry();
builder.Services.AddHttpLogging(logging =>
{
    logging.LoggingFields = HttpLoggingFields.All;
    logging.RequestHeaders.Add(WellKnownHttpHeaders.CorrelationId);
    logging.ResponseHeaders.Add(WellKnownHttpHeaders.CorrelationId);
    logging.ResponseHeaders.Add("X-Total-Count");
    logging.ResponseHeaders.Add("X-Limit");
    logging.ResponseHeaders.Add("Link");
    logging.RequestBodyLogLimit = 4096;
    logging.ResponseBodyLogLimit = 4096;
    logging.MediaTypeOptions.AddText("application/json");
});
builder.Logging.AddFilter<ApplicationInsightsLoggerProvider>(
    "Microsoft.AspNetCore.HttpLogging.HttpLoggingMiddleware",
    LogLevel.Trace);
```

The `AddFilter<ApplicationInsightsLoggerProvider>()` is used get it to write directly to app insights as trace telemetry

**Review by davidkallesen — APPROVED** [review]

**Comment by perkops** [comment]
We are atm not using azure, anyhow - we already tried the Add HttpLogging but didnt get wanted results, with this approach (which is opt-in), we are getting something like:

```json{
    "system": "redacted",
    "request": {
        "dateTimeUtc": "2022-11-11T09:23:09.0372004Z",
        "requestId": "8000001f-0008-fe00-b63f-84710c7967bb",
        "clientIp": "127.0.0.1",
        "method": "GET",
        "scheme": "https",
        "host": "localhost:44321",
        "path": "/api/v1/folder",
        "queryString": "?opcUaUrl=opc.tcp://127.0.0.1:49320/\u0026folderNodeId=ns=2;s=Channel1.Device1",
        "queryParameters": [{
                "key": "opcUaUrl",
                "value": "opc.tcp://127.0.0.1:49320/"
            }
        ],
        "headerParameters": {
            "Host": "localhost:44321",
            "x-correlation-id": "17c910a0-fc4c-4e85-8a2f-e761e696acf6",
            "x-request-id": "B13BCCBB-2CC5-4056-8ADD-968739746BA6"
        },
        "body": ""
    },
    "response": {
        "dateTimeUtc": "2022-11-11T09:23:12.1523291Z",
        "status": "200",
        "headerParameters": {
            "x-correlation-id": "17c910a0-fc4c-4e85-8a2f-e761e696acf6",
            "Content-Type": "application/json; charset=utf-8; v=1.0",
            "api-supported-versions": "1.0"
        },
        "contentType": "application/json; charset=utf-8; v=1.0",
        "body": "redacted"
    },
    "executionTime": "3.115 sec"
}
```

**Pull request merged**
